### ISSUE TITLE
About QM9 dataset

### ISSUE THREAD

**Issue by hyunjin72** [Rich-XGK/GTMGC#3]
Hello, thanks for your great work!
I've been working on reproducing GTMGC on QM9 dataset, but I noticed that some edge attributes contain elements that are all zeros. As far as I know, edge attributes should be one hot matrices indicating one of the four bond types. 
Could you clarify this issue?

**Comment by Rich-XGK** [comment]
Thank you very much for your attention! During our data preprocessing, we use the OGB format for node and edge features. Each edge feature is a multi-dimensional vector, where each position represents the index of a certain edge property in the corresponding attribute list. You can refer to the bond_to_feature_vector function in ./molecule3d/utils.py and the EdgeEmbedding and BondEmbedding classes in ./models/modules/embedding.py to learn more. If you have any further questions or need clarification, please feel free to contact me at richxu945@gmail.com with more details.

Let me know if you need any further adjustments!
